### ISSUE TITLE
Segfault when using single colon instead of double on lquery

### ISSUE THREAD

**Issue by mrimbault** [adjust/wltree#20]
It seems that segfault occurs when one mistakenly use only one colon at a place where the full separator would be expected, like after a `*` on a `lquery` string.

How to reproduce:
```
# select '*:test'::lquery  ;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

Using full separator, or something that is not part of the separator does not trigger the segfault:
```
# select '*::test'::lquery ;
 lquery
---------
 *::test
(1 row)

# select '*.test'::lquery ;
ERROR:  syntax error at position 1: '.'
LINE 1: select '*.test'::lquery ;
               ^

```

This is with the extension built from master.
Extension version:
```
# \dx wltree
                                      List of installed extensions
  Name  | Version | Schema |                                 Description
--------+---------+--------+-----------------------------------------------------------------------------
 wltree | 2.0     | public | data type for hierarchical tree-like structures with wide character support
(1 row)
```

And with PG 13.1 (also reproduced with PG 12.4.

**Comment by za-arthur** [comment]
@mrimbault @andreasscherbaum I've created pull request https://github.com/adjust/wltree/pull/15 which fixes this.

**Comment by andreasscherbaum** [comment]
https://github.com/adjust/wltree/pull/15 is a different PR, you created https://github.com/adjust/wltree/pull/21.
(for reference both mentioned here)

**Comment by andreasscherbaum** [comment]
@scorpevans Please update this issue with the list of hosts which have this extension installed.

**Comment by alexeyklyukin** [comment]
Suggestion: as this is, in fact, a public repo, perhaps the list of hosts should be exposed somewhere else...
