### ISSUE TITLE
Kudos to the effort

### ISSUE THREAD

**Issue by Charizard** [adjust/wltree#4]
Hey, just wanted to say that this project is an awesome effort in removing the character limit of label's in ltree.

I have a few question though. What was the main idea / reason behind this patch? Because I need to understand if there are any drawbacks in allowing all characters. Also, I need only hyphen( - ) to be allowed in the label's and not all characters.

Also, what is the reason behind escaping the special characters like `{ } % ! *` while querying?

Thanks.

**Comment by einhverfr** [comment]
The idea was to allow ltrees with wide characters (such as Chinese characters).  This allows input labels that work on any UTF-8 string.
